#!/usr/bin/env python3
"""Authenticate an out-of-band site build against the checkout that publishes it.

The blueprint site is generated by the verify workflow's site-generate job,
packaged into a tarball on a GitHub Release, and pinned by a file committed to
the publish branch (`site/trust/site-build.json` by default) that names the
release asset and pins its SHA-256. Pages then serves the PINNED asset rather
than whatever the last run happened to upload. This script is the gate between
the two. It is what turns "somebody uploaded a tarball" into "the publish branch
vouches for these bytes, and these bytes describe the publish branch".

It is deliberately not "does the pin's hash match the download". A hash pin proves
the operator uploaded what they pinned; it proves nothing about what the site says.
So the gate also opens the tarball and reads the generator's own provenance record
(`-verso-data/trust-provenance.json`, the same document a362583's publish job
authenticates before it uploads a Pages artifact) and holds it to the checkout:

  * the record's generation revision is the pin's, is not dirty, and is on the
    history of the commit being published (an ancestor of HEAD, or HEAD itself);
  * every elaboration-time trust input the record lists -- formalization.yaml, the
    comparator status record, its config, the challenge and solution files --
    still hashes, AT THE CHECKOUT, to what the generator read. This is the CX-075
    property: a site whose comparator page quotes a verdict master has since
    replaced does not deploy, it gets regenerated;
  * every project-local blob link names the generation revision (a362583's CX-066
    gate), so the links the trust model promises are checkable. That is TWO
    surfaces, not one: the declaration registry, whose links are bound late (at
    emission, from the build stamp), and the rendered HTML, where the comparator
    page's "View on GitHub" links are composed at ELABORATION and baked into an
    `.olean` a later generation replays verbatim;
  * the surfaces that probe-and-degrade are on disk (index, manifest, the
    comparator page, the trust-model page) and the tree is neither trivially small
    nor over the size GitHub Pages will publish.

Off-origin asset gates over the HTML are a separate shell script
(ci/scripts/site_offline_gates.sh), shared with the packaging step, so the tree
is refused for the same reasons in the job that generated it and in the job that
would deploy it.

This is the one copy, shared by every consumer of the reusable workflow. Two
things are arguments rather than constants because consumers differ: the site
package directory the recorded input paths resolve against (`--site-dir`: `site`
for a nested site package, `.` for lean_quine) and the surfaces that must be on
disk (`--required-file`, repeatable).

The verify workflow's `Gates` step runs the source-link half of this gate alone,
over the tree it has just generated, with `--links-only`. Same regex, same two
surfaces, one implementation: a second copy inlined in the workflow is precisely
how the generation-time gate stayed registry-only while the deploy-time one was
meant to be its twin.

Exit status 0 means "publish"; anything else prints every failed property and
exits 1. Run: python3 ci/scripts/check_site_release.py --help
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys

# The pin document this script understands, exactly (ci/scripts/package_site.sh
# writes it). Bump together with the writer, in a commit that says what changed.
#
# Version 2 adds `producer` -- WHICH run of WHICH CI code packaged this site --
# and widens `pins` from a hardcoded four packages to every package in the site
# workspace's manifest. Version 1 is not accepted: a document this gate has no
# checks for is not a document it may pass.
PIN_SCHEMA_VERSION = 2

# The generator's provenance document, exactly. It is `provenanceSchemaVersion`
# in the fork's `VersoBlueprint.TrustFreshness`; a fork that changes the document
# bumps that number and this constant moves with it deliberately.
PROVENANCE_SCHEMA_VERSION = 1

# Roles the record must carry for this consumer: both are configured in
# site/lakefile.lean (`trust.formalizationYaml`, `trust.comparatorStatus`) and both
# are what the trust surfaces quote. A record that lists neither is a record of
# some other build.
DEFAULT_REQUIRED_ROLES = ("formalization-yaml", "comparator-status")

# Surfaces that the generator writes only when their inputs were read
# successfully; their absence is the quiet regression this gate exists for.
DEFAULT_REQUIRED_FILES = (
    "index.html",
    os.path.join("-verso-data", "blueprint-manifest.json"),
    os.path.join("-verso-data", "decl-registry.json"),
    os.path.join("-verso-data", "trust-provenance.json"),
    os.path.join("comparator", "index.html"),
    os.path.join("Trust-model", "index.html"),
)

HEX40 = re.compile(r"\A[0-9a-f]{40}\Z")
HEX64 = re.compile(r"\A[0-9a-f]{64}\Z")


def sha256_of(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def tree_stats(root):
    files = 0
    total = 0
    for dirpath, _dirnames, filenames in os.walk(root):
        for name in filenames:
            files += 1
            total += os.path.getsize(os.path.join(dirpath, name))
    return files, total


def is_ancestor(repo_root, ancestor, descendant):
    result = subprocess.run(
        ["git", "-C", repo_root, "merge-base", "--is-ancestor", ancestor, descendant],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return result.returncode == 0


def load_json(path, failures, what):
    try:
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, ValueError) as error:
        failures.append("{}: cannot read {}: {}".format(what, path, error))
        return None


def check_pin(pin, failures):
    if not isinstance(pin, dict):
        failures.append("pin: not a JSON object")
        return None
    if pin.get("schemaVersion") != PIN_SCHEMA_VERSION:
        failures.append(
            "pin: schemaVersion {!r}, this gate understands exactly {}".format(
                pin.get("schemaVersion"), PIN_SCHEMA_VERSION
            )
        )
    revision = pin.get("generationRevision")
    if not isinstance(revision, str) or not HEX40.match(revision):
        failures.append("pin: generationRevision is not a full 40-hex commit")
        revision = None
    release = pin.get("release")
    if not isinstance(release, dict):
        failures.append("pin: no release object")
        return revision
    for key in ("tag", "asset"):
        if not isinstance(release.get(key), str) or not release[key]:
            failures.append("pin: release.{} missing".format(key))
    digest = release.get("sha256")
    if not isinstance(digest, str) or not HEX64.match(digest):
        failures.append("pin: release.sha256 is not a SHA-256 hex digest")
    if not isinstance(release.get("bytes"), int) or release["bytes"] <= 0:
        failures.append("pin: release.bytes is not a positive integer")
    pins = pin.get("pins")
    if not isinstance(pins, dict) or not pins:
        failures.append("pin: no `pins` map (the dependency revisions the site was built from)")
    elif not isinstance(pins.get("toolchain"), str) or not pins["toolchain"]:
        failures.append("pin: pins.toolchain is missing")
    # WHICH run of WHICH CI code packaged this. The workflow that produced the
    # tarball is in a different repository from the site, so "CI built this" is a
    # claim about a commit over there; the pin has to name it.
    producer = pin.get("producer")
    if not isinstance(producer, dict):
        failures.append("pin: no `producer` object; the pin names no CI code")
        return revision
    workflow_sha = producer.get("workflow_sha")
    if not isinstance(workflow_sha, str) or not HEX40.match(workflow_sha):
        failures.append("pin: producer.workflow_sha is not a full 40-hex commit")
    for key in ("workflow_repository", "workflow_ref", "run_id", "run_url"):
        value = producer.get(key)
        if not isinstance(value, str) or not value:
            failures.append("pin: producer.{} is missing".format(key))
    return revision


def check_tarball(pin, tarball, failures):
    release = pin.get("release") if isinstance(pin, dict) else None
    if not isinstance(release, dict):
        return
    if not os.path.isfile(tarball):
        failures.append("tarball: {} does not exist".format(tarball))
        return
    actual = sha256_of(tarball)
    if actual != release.get("sha256"):
        failures.append(
            "tarball: sha256 {} does not match the pinned {}".format(actual, release.get("sha256"))
        )
    size = os.path.getsize(tarball)
    if size != release.get("bytes"):
        failures.append("tarball: {} bytes, the pin says {}".format(size, release.get("bytes")))


def check_provenance(site_root, revision, head, repo_root, site_dir, repository,
                     required_roles, failures):
    record = load_json(
        os.path.join(site_root, "-verso-data", "trust-provenance.json"), failures, "provenance"
    )
    if record is None:
        return
    if record.get("schemaVersion") != PROVENANCE_SCHEMA_VERSION:
        failures.append(
            "provenance: schemaVersion {!r}, this gate understands exactly {}".format(
                record.get("schemaVersion"), PROVENANCE_SCHEMA_VERSION
            )
        )
    build = record.get("buildRevision")
    if not isinstance(build, dict):
        failures.append("provenance: no buildRevision object")
        build = {}
    commit = build.get("commit")
    if not isinstance(commit, str) or not HEX40.match(commit):
        failures.append("provenance: buildRevision.commit is not a full 40-hex commit")
    elif revision is not None and commit != revision:
        failures.append(
            "provenance: generated at {} but the pin vouches for {}".format(commit, revision)
        )
    if build.get("dirty") is not False:
        failures.append(
            "provenance: buildRevision.dirty is {!r}; a site generated from an uncommitted "
            "worktree describes no commit and does not deploy".format(build.get("dirty"))
        )
    if repository:
        url = build.get("repositoryUrl")
        expected = "https://github.com/{}".format(repository)
        if url != expected:
            failures.append(
                "provenance: repositoryUrl {!r} is not {}".format(url, expected)
            )
    if revision is not None and head is not None:
        if not is_ancestor(repo_root, revision, head):
            failures.append(
                "provenance: generation revision {} is not on the history of {} "
                "(the commit being published)".format(revision, head)
            )
    inputs = record.get("inputs")
    if not isinstance(inputs, list) or not inputs:
        failures.append("provenance: no inputs recorded")
        return
    input_root = os.path.normpath(os.path.join(repo_root, site_dir))
    roles = set()
    for entry in inputs:
        if not isinstance(entry, dict):
            failures.append("provenance: malformed input entry {!r}".format(entry))
            continue
        path = entry.get("path")
        role = entry.get("role")
        recorded = entry.get("sha256")
        if not isinstance(path, str) or not isinstance(recorded, str):
            failures.append("provenance: input entry without path/sha256: {!r}".format(entry))
            continue
        roles.add(role)
        resolved = os.path.normpath(os.path.join(input_root, path))
        if not os.path.isfile(resolved):
            failures.append(
                "provenance: input {} ({}) is not in the checkout at {}".format(path, role, resolved)
            )
            continue
        actual = sha256_of(resolved)
        if actual != recorded:
            failures.append(
                "provenance: input {} ({}) hashes {} at the checkout, the site read {} -- "
                "master has moved past this build; regenerate".format(path, role, actual, recorded)
            )
    for role in required_roles:
        if role not in roles:
            failures.append("provenance: no input with role {!r}".format(role))


# The one regex both source-link checks use, so the two surfaces cannot drift
# apart in what they consider a project-local link. `repository` is `owner/name`;
# the capture is the revision the link names. Links into OTHER repositories --
# mathlib, a dependency checkout whose revision the lockfile pins -- are out of
# scope by construction: their revision is not ours to be stale.
PROJECT_BLOB_TEMPLATE = r"https://github\.com/{}/blob/([0-9a-f]{{40}})/"


def project_blob_pattern(repository):
    return re.compile(PROJECT_BLOB_TEMPLATE.format(re.escape(repository)))


def check_source_links(site_root, revision, repository, failures):
    """The declaration registry's `sourceHref` values.

    These are bound at EMISSION from the same revision the build stamp reads, so
    a stale one means the registry itself was replayed from a build warmed at
    another commit. This check keeps its vacuity guard: a blueprint site with no
    project-local registry link is a registry that moved, not a site with nothing
    to say.
    """
    if revision is None or not repository:
        return
    registry = load_json(
        os.path.join(site_root, "-verso-data", "decl-registry.json"), failures, "registry"
    )
    if registry is None:
        return
    pattern = project_blob_pattern(repository)
    checked = 0
    stale = {}

    def visit(node):
        nonlocal checked
        if isinstance(node, dict):
            href = node.get("sourceHref")
            if isinstance(href, str):
                found = pattern.match(href)
                if found:
                    checked += 1
                    if found.group(1) != revision:
                        stale[found.group(1)] = stale.get(found.group(1), 0) + 1
            for value in node.values():
                visit(value)
        elif isinstance(node, list):
            for value in node:
                visit(value)

    visit(registry)
    if checked == 0:
        failures.append(
            "source links: no project-local sourceHref in the registry -- the gate is vacuous, "
            "so either the registry moved or the links stopped naming this repository"
        )
    if stale:
        detail = ", ".join(
            "{} link(s) name {}".format(count, sha) for sha, count in sorted(stale.items())
        )
        failures.append(
            "source links: {} of {} project-local source links do not name the generation "
            "revision {} ({})".format(sum(stale.values()), checked, revision, detail)
        )
    # The count is the record of what the gate actually looked at; a run whose
    # log says 13 and a run whose log says 0 mean very different things about a
    # green result.
    print("decl registry: {} project-local source link(s)".format(checked))


def check_html_source_links(site_root, revision, repository, failures):
    """Project-local blob links in the RENDERED HTML.

    The registry is not the only surface that publishes source links, and it is
    the only one bound late. The comparator page's "View on GitHub" links are
    composed at ELABORATION from the repository HEAD of that moment
    (`Git.repositoryInfoAtRoot?`), baked into the embedding module's `.olean`,
    and replayed verbatim by any later generation that reuses it. So a site whose
    contents were elaborated one commit before it was generated publishes a
    comparator page pointing at the previous commit while its registry, and its
    build stamp, name the current one -- measured during the lean_quine adoption,
    three stale links, registry-only gate green.

    Unlike the registry check this one has NO vacuity guard, deliberately: a
    consumer may legitimately render no project-local blob link at all (no
    comparator page, no repository remote). Zero is reported, not refused.
    """
    if revision is None or not repository:
        return
    # Matched over raw bytes: these URLs are ASCII, every page is read anyway,
    # and decoding a multi-hundred-megabyte tree to find them is pure cost.
    pattern = re.compile(project_blob_pattern(repository).pattern.encode("utf-8"))
    wanted = revision.encode("utf-8")
    checked = 0
    pages = 0
    stale = {}
    stale_pages = []
    for dirpath, _dirnames, filenames in os.walk(site_root):
        for name in sorted(filenames):
            if not name.endswith((".html", ".htm")):
                continue
            path = os.path.join(dirpath, name)
            try:
                with open(path, "rb") as handle:
                    body = handle.read()
            except OSError as error:
                failures.append("html source links: cannot read {}: {}".format(path, error))
                continue
            found = pattern.findall(body)
            if not found:
                continue
            pages += 1
            checked += len(found)
            bad = [sha for sha in found if sha != wanted]
            if bad:
                stale_pages.append(os.path.relpath(path, site_root))
                for sha in bad:
                    key = sha.decode("utf-8")
                    stale[key] = stale.get(key, 0) + 1
    if stale:
        detail = ", ".join(
            "{} link(s) name {}".format(count, sha) for sha, count in sorted(stale.items())
        )
        listed = sorted(stale_pages)
        shown = ", ".join(listed[:5])
        if len(listed) > 5:
            shown += ", and {} more page(s)".format(len(listed) - 5)
        failures.append(
            "html source links: {} of {} project-local blob links in the rendered HTML do not "
            "name the generation revision {} ({}); on {}".format(
                sum(stale.values()), checked, revision, detail, shown
            )
        )
    if checked:
        print(
            "html source links: {} project-local blob link(s) across {} HTML page(s)".format(
                checked, pages
            )
        )
    else:
        print("html source links: none in the rendered HTML (nothing to check)")


def check_tree(site_root, required_files, min_files, max_bytes, failures):
    if not os.path.isdir(site_root):
        failures.append("tree: {} is not a directory".format(site_root))
        return
    for relative in required_files:
        if not os.path.isfile(os.path.join(site_root, relative)):
            failures.append("tree: {} is missing".format(relative))
    files, total = tree_stats(site_root)
    if files < min_files:
        failures.append("tree: only {} files (floor {})".format(files, min_files))
    if total > max_bytes:
        failures.append(
            "tree: {} bytes exceeds the {} bytes GitHub Pages will publish".format(total, max_bytes)
        )
    print("tree: {} files, {} bytes".format(files, total))


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Authenticate an out-of-band site build before publishing it."
    )
    parser.add_argument("--pin", help="site/trust/site-build.json")
    parser.add_argument("--tarball", help="the downloaded release asset")
    parser.add_argument(
        "--site-root", required=True, help="the extracted html-multi directory"
    )
    parser.add_argument(
        "--repo-root", help="the checkout the site is being published from"
    )
    parser.add_argument(
        "--head", help="the commit being published (git rev-parse HEAD)"
    )
    parser.add_argument(
        "--links-only",
        action="store_true",
        help="run ONLY the source-link revision gate (CX-066) over --site-root against"
             " --revision, and exit. The mode the verify workflow's `Gates` step invokes,"
             " so the gate a site is generated under and the gate the deploy path re-runs"
             " are one implementation rather than two copies that drifted.",
    )
    parser.add_argument(
        "--revision",
        default="",
        help="the generation revision, for --links-only; the full gate reads it off the pin",
    )
    parser.add_argument(
        "--repository",
        default="",
        help="owner/name, for the repositoryUrl and source-link checks (empty skips them)",
    )
    parser.add_argument(
        "--site-dir",
        default="site",
        help="the site package directory, relative to --repo-root; the paths the"
             " generator recorded resolve against it (`site` for a nested site"
             " package, `.` when the site is the repository root)",
    )
    parser.add_argument(
        "--required-file",
        action="append",
        default=[],
        metavar="RELATIVE",
        help="a surface that must be on disk under --site-root; repeatable."
             " Defaults to the full blueprint set when not given.",
    )
    parser.add_argument(
        "--required-role",
        action="append",
        default=[],
        metavar="ROLE",
        help="a trust-input role the provenance record must carry; repeatable."
             " Defaults to formalization-yaml + comparator-status.",
    )
    parser.add_argument("--min-files", type=int, default=50)
    parser.add_argument(
        "--max-bytes",
        type=int,
        default=900_000_000,
        help="the gate for one GitHub Pages site (the documented limit is 1 GB; deployments near it time out)",
    )
    args = parser.parse_args(argv)

    if args.links_only:
        # Nothing here may be inferred from what is on disk: this gate is a
        # declared capability of the calling workflow, and a run that skipped it
        # because an argument was empty would be the probe-and-degrade weakness
        # the standard rejects.
        for flag, value in (("--repository", args.repository), ("--revision", args.revision)):
            if not value:
                parser.error("--links-only requires {}".format(flag))
        if not HEX40.match(args.revision):
            parser.error("--revision {!r} is not a full 40-hex commit".format(args.revision))
        failures = []
        check_source_links(args.site_root, args.revision, args.repository, failures)
        check_html_source_links(args.site_root, args.revision, args.repository, failures)
        if failures:
            print("source-link gate: REFUSED")
            for failure in failures:
                print("  - " + failure)
            print("the site publishes source links naming a revision it was not generated")
            print("from; rebuild it under this commit rather than publishing a stamp its")
            print("own links contradict.")
            return 1
        print("source-link gate: every project-local source link names " + args.revision)
        return 0

    missing = [
        flag
        for flag, value in (
            ("--pin", args.pin),
            ("--tarball", args.tarball),
            ("--repo-root", args.repo_root),
            ("--head", args.head),
        )
        if not value
    ]
    if missing:
        parser.error("required unless --links-only: " + ", ".join(missing))

    required_files = tuple(args.required_file) or DEFAULT_REQUIRED_FILES
    required_roles = tuple(args.required_role) or DEFAULT_REQUIRED_ROLES

    failures = []
    pin = load_json(args.pin, failures, "pin")
    revision = check_pin(pin, failures) if pin is not None else None
    if pin is not None:
        check_tarball(pin, args.tarball, failures)
    check_tree(args.site_root, required_files, args.min_files, args.max_bytes, failures)
    check_provenance(
        args.site_root, revision, args.head, args.repo_root, args.site_dir,
        args.repository, required_roles, failures
    )
    check_source_links(args.site_root, revision, args.repository, failures)
    check_html_source_links(args.site_root, revision, args.repository, failures)

    if failures:
        print("site release gate: REFUSED")
        for failure in failures:
            print("  - " + failure)
        return 1
    print(
        "site release gate: {} generated at {} is vouched for by {}".format(
            os.path.basename(args.tarball), revision, args.head
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
